name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build
        run: mvn clean install

      - name: Rodar testes
        run: mvn test

      - name: Build Docker image
        run: docker build -t greenflow .

  deploy-staging:
    needs: build-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'

    steps:
      - name: Deploy STAGING
        run: echo "Aplicação enviada para STAGING 🚀"

  deploy-production:
    needs: build-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy PRODUÇÃO
        run: echo "Aplicação enviada para PRODUÇÃO 🚀"